POST http://localhost:8080/api/v1/users/register
Accept: application/json
Content-Type: application/json

{
    "username": "x"
}

###

POST http://localhost:8080/api/v1/users/login
Accept: application/json
Content-Type: application/json

{
    "username": "x"
}

###

POST http://localhost:8080/api/v1/users/logout

###

POST http://localhost:8080/api/v1/todo
Accept: application/json
Content-Type: application/json

{
    "name": "",
    "user_id": 1,
    "group_id": 2
}

### 

PATCH http://localhost:8080/api/v1/todo
Accept: application/json
Content-Type: application/json

{
    "id": 1,
    "name": "sleep",
    "user_id": 1,
    "group_id": 1
}

### 

GET http://localhost:8080/api/v1/todo/x

###

DELETE http://localhost:8080/api/v1/todo/1