POST http://localhost:8080/api/v1/users/register
Accept: application/json
Content-Type: application/json

{
    "username": "x",
    "password": "xx"
}

###

POST http://localhost:8080/api/v1/users/login
Accept: application/json
Content-Type: application/json

{
    "username": "x",
    "password": "xx"
}

###

POST http://localhost:8080/api/v1/users/logout

###

POST http://localhost:8080/api/v1/todo
Accept: application/json
Content-Type: application/json

{
    "name": "?",
    "userId": 1,
    "groupId": 2
}

### 

PATCH http://localhost:8080/api/v1/todo/1
Accept: application/json
Content-Type: application/json

{
    "name": "?",
    "userId": 1,
    "groupId": 1
}

### 

GET http://localhost:8080/api/v1/todo/x

###

DELETE http://localhost:8080/api/v1/todo/1

###

PATCH http://localhost:8080/api/v1/todo/container/priority/3
Accept: application/json
Content-Type: application/json

{
  "originPriority": 2,
  "targetId": 2,
  "targetPriority": 3
}

###
POST http://localhost:8080/api/v1/todo/container
Accept: application/json
Content-Type: application/json

{
    "userId": 1,
    "groupName": "pending",
    "priority": 4
}

###
POST http://localhost:8080/api/v1/todo/container
Accept: application/json
Content-Type: application/json

{
    "userId": 1,
    "groupName": "later",
    "priority": 5
}